# -*- coding: utf-8 -*-
"""Spencer Werhan 24 Lab 2.5 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DoK6HQMVYVer43deflzUKkajraIrJHqg
"""

import numpy as np
import matplotlib.pyplot as plt

"""# PRNG"""

x = 0.12345

x = x*3

x % 1

current_point = 0.12345          # seed value
points_to_save = np.zeros(50000,)  # initialize an array of zeros

for i in range(points_to_save.shape[0]):
    current_point = 3*current_point % 1      # update x and store the value in X
    points_to_save[i] = current_point

plt.plot(points_to_save, '.')     # plot the values in X

